// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountthrottlerule"
)

// AccountThrottleRule is the model entity for the AccountThrottleRule schema.
type AccountThrottleRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// ErrorCodes holds the value of the "error_codes" field.
	ErrorCodes []int `json:"error_codes,omitempty"`
	// Keywords holds the value of the "keywords" field.
	Keywords []string `json:"keywords,omitempty"`
	// MatchMode holds the value of the "match_mode" field.
	MatchMode string `json:"match_mode,omitempty"`
	// TriggerMode holds the value of the "trigger_mode" field.
	TriggerMode string `json:"trigger_mode,omitempty"`
	// AccumulatedCount holds the value of the "accumulated_count" field.
	AccumulatedCount int `json:"accumulated_count,omitempty"`
	// AccumulatedWindow holds the value of the "accumulated_window" field.
	AccumulatedWindow int `json:"accumulated_window,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType string `json:"action_type,omitempty"`
	// ActionDuration holds the value of the "action_duration" field.
	ActionDuration int `json:"action_duration,omitempty"`
	// ActionRecoverHour holds the value of the "action_recover_hour" field.
	ActionRecoverHour int `json:"action_recover_hour,omitempty"`
	// Platforms holds the value of the "platforms" field.
	Platforms []string `json:"platforms,omitempty"`
	// Description holds the value of the "description" field.
	Description  *string `json:"description,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountThrottleRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountthrottlerule.FieldErrorCodes, accountthrottlerule.FieldKeywords, accountthrottlerule.FieldPlatforms:
			values[i] = new([]byte)
		case accountthrottlerule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case accountthrottlerule.FieldID, accountthrottlerule.FieldPriority, accountthrottlerule.FieldAccumulatedCount, accountthrottlerule.FieldAccumulatedWindow, accountthrottlerule.FieldActionDuration, accountthrottlerule.FieldActionRecoverHour:
			values[i] = new(sql.NullInt64)
		case accountthrottlerule.FieldName, accountthrottlerule.FieldMatchMode, accountthrottlerule.FieldTriggerMode, accountthrottlerule.FieldActionType, accountthrottlerule.FieldDescription:
			values[i] = new(sql.NullString)
		case accountthrottlerule.FieldCreatedAt, accountthrottlerule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountThrottleRule fields.
func (_m *AccountThrottleRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountthrottlerule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountthrottlerule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountthrottlerule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountthrottlerule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountthrottlerule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case accountthrottlerule.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case accountthrottlerule.FieldErrorCodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field error_codes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ErrorCodes); err != nil {
					return fmt.Errorf("unmarshal field error_codes: %w", err)
				}
			}
		case accountthrottlerule.FieldKeywords:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field keywords", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Keywords); err != nil {
					return fmt.Errorf("unmarshal field keywords: %w", err)
				}
			}
		case accountthrottlerule.FieldMatchMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_mode", values[i])
			} else if value.Valid {
				_m.MatchMode = value.String
			}
		case accountthrottlerule.FieldTriggerMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_mode", values[i])
			} else if value.Valid {
				_m.TriggerMode = value.String
			}
		case accountthrottlerule.FieldAccumulatedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accumulated_count", values[i])
			} else if value.Valid {
				_m.AccumulatedCount = int(value.Int64)
			}
		case accountthrottlerule.FieldAccumulatedWindow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accumulated_window", values[i])
			} else if value.Valid {
				_m.AccumulatedWindow = int(value.Int64)
			}
		case accountthrottlerule.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = value.String
			}
		case accountthrottlerule.FieldActionDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action_duration", values[i])
			} else if value.Valid {
				_m.ActionDuration = int(value.Int64)
			}
		case accountthrottlerule.FieldActionRecoverHour:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action_recover_hour", values[i])
			} else if value.Valid {
				_m.ActionRecoverHour = int(value.Int64)
			}
		case accountthrottlerule.FieldPlatforms:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field platforms", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Platforms); err != nil {
					return fmt.Errorf("unmarshal field platforms: %w", err)
				}
			}
		case accountthrottlerule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountThrottleRule.
// This includes values selected through modifiers, order, etc.
func (_m *AccountThrottleRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountThrottleRule.
// Note that you need to call AccountThrottleRule.Unwrap() before calling this method if this AccountThrottleRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountThrottleRule) Update() *AccountThrottleRuleUpdateOne {
	return NewAccountThrottleRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountThrottleRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountThrottleRule) Unwrap() *AccountThrottleRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountThrottleRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountThrottleRule) String() string {
	var builder strings.Builder
	builder.WriteString("AccountThrottleRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("error_codes=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCodes))
	builder.WriteString(", ")
	builder.WriteString("keywords=")
	builder.WriteString(fmt.Sprintf("%v", _m.Keywords))
	builder.WriteString(", ")
	builder.WriteString("match_mode=")
	builder.WriteString(_m.MatchMode)
	builder.WriteString(", ")
	builder.WriteString("trigger_mode=")
	builder.WriteString(_m.TriggerMode)
	builder.WriteString(", ")
	builder.WriteString("accumulated_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccumulatedCount))
	builder.WriteString(", ")
	builder.WriteString("accumulated_window=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccumulatedWindow))
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(_m.ActionType)
	builder.WriteString(", ")
	builder.WriteString("action_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionDuration))
	builder.WriteString(", ")
	builder.WriteString("action_recover_hour=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionRecoverHour))
	builder.WriteString(", ")
	builder.WriteString("platforms=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platforms))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccountThrottleRules is a parsable slice of AccountThrottleRule.
type AccountThrottleRules []*AccountThrottleRule
