// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountthrottlerule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountThrottleRuleUpdate is the builder for updating AccountThrottleRule entities.
type AccountThrottleRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AccountThrottleRuleMutation
}

// Where appends a list predicates to the AccountThrottleRuleUpdate builder.
func (_u *AccountThrottleRuleUpdate) Where(ps ...predicate.AccountThrottleRule) *AccountThrottleRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountThrottleRuleUpdate) SetUpdatedAt(v time.Time) *AccountThrottleRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountThrottleRuleUpdate) SetName(v string) *AccountThrottleRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableName(v *string) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AccountThrottleRuleUpdate) SetEnabled(v bool) *AccountThrottleRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableEnabled(v *bool) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AccountThrottleRuleUpdate) SetPriority(v int) *AccountThrottleRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillablePriority(v *int) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AccountThrottleRuleUpdate) AddPriority(v int) *AccountThrottleRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *AccountThrottleRuleUpdate) SetKeywords(v []string) *AccountThrottleRuleUpdate {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *AccountThrottleRuleUpdate) AppendKeywords(v []string) *AccountThrottleRuleUpdate {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *AccountThrottleRuleUpdate) ClearKeywords() *AccountThrottleRuleUpdate {
	_u.mutation.ClearKeywords()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *AccountThrottleRuleUpdate) SetMatchMode(v string) *AccountThrottleRuleUpdate {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableMatchMode(v *string) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// SetTriggerMode sets the "trigger_mode" field.
func (_u *AccountThrottleRuleUpdate) SetTriggerMode(v string) *AccountThrottleRuleUpdate {
	_u.mutation.SetTriggerMode(v)
	return _u
}

// SetNillableTriggerMode sets the "trigger_mode" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableTriggerMode(v *string) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetTriggerMode(*v)
	}
	return _u
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (_u *AccountThrottleRuleUpdate) SetAccumulatedCount(v int) *AccountThrottleRuleUpdate {
	_u.mutation.ResetAccumulatedCount()
	_u.mutation.SetAccumulatedCount(v)
	return _u
}

// SetNillableAccumulatedCount sets the "accumulated_count" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableAccumulatedCount(v *int) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetAccumulatedCount(*v)
	}
	return _u
}

// AddAccumulatedCount adds value to the "accumulated_count" field.
func (_u *AccountThrottleRuleUpdate) AddAccumulatedCount(v int) *AccountThrottleRuleUpdate {
	_u.mutation.AddAccumulatedCount(v)
	return _u
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (_u *AccountThrottleRuleUpdate) SetAccumulatedWindow(v int) *AccountThrottleRuleUpdate {
	_u.mutation.ResetAccumulatedWindow()
	_u.mutation.SetAccumulatedWindow(v)
	return _u
}

// SetNillableAccumulatedWindow sets the "accumulated_window" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableAccumulatedWindow(v *int) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetAccumulatedWindow(*v)
	}
	return _u
}

// AddAccumulatedWindow adds value to the "accumulated_window" field.
func (_u *AccountThrottleRuleUpdate) AddAccumulatedWindow(v int) *AccountThrottleRuleUpdate {
	_u.mutation.AddAccumulatedWindow(v)
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *AccountThrottleRuleUpdate) SetActionType(v string) *AccountThrottleRuleUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableActionType(v *string) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionDuration sets the "action_duration" field.
func (_u *AccountThrottleRuleUpdate) SetActionDuration(v int) *AccountThrottleRuleUpdate {
	_u.mutation.ResetActionDuration()
	_u.mutation.SetActionDuration(v)
	return _u
}

// SetNillableActionDuration sets the "action_duration" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableActionDuration(v *int) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetActionDuration(*v)
	}
	return _u
}

// AddActionDuration adds value to the "action_duration" field.
func (_u *AccountThrottleRuleUpdate) AddActionDuration(v int) *AccountThrottleRuleUpdate {
	_u.mutation.AddActionDuration(v)
	return _u
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (_u *AccountThrottleRuleUpdate) SetActionRecoverHour(v int) *AccountThrottleRuleUpdate {
	_u.mutation.ResetActionRecoverHour()
	_u.mutation.SetActionRecoverHour(v)
	return _u
}

// SetNillableActionRecoverHour sets the "action_recover_hour" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableActionRecoverHour(v *int) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetActionRecoverHour(*v)
	}
	return _u
}

// AddActionRecoverHour adds value to the "action_recover_hour" field.
func (_u *AccountThrottleRuleUpdate) AddActionRecoverHour(v int) *AccountThrottleRuleUpdate {
	_u.mutation.AddActionRecoverHour(v)
	return _u
}

// SetPlatforms sets the "platforms" field.
func (_u *AccountThrottleRuleUpdate) SetPlatforms(v []string) *AccountThrottleRuleUpdate {
	_u.mutation.SetPlatforms(v)
	return _u
}

// AppendPlatforms appends value to the "platforms" field.
func (_u *AccountThrottleRuleUpdate) AppendPlatforms(v []string) *AccountThrottleRuleUpdate {
	_u.mutation.AppendPlatforms(v)
	return _u
}

// ClearPlatforms clears the value of the "platforms" field.
func (_u *AccountThrottleRuleUpdate) ClearPlatforms() *AccountThrottleRuleUpdate {
	_u.mutation.ClearPlatforms()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountThrottleRuleUpdate) SetDescription(v string) *AccountThrottleRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdate) SetNillableDescription(v *string) *AccountThrottleRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountThrottleRuleUpdate) ClearDescription() *AccountThrottleRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AccountThrottleRuleMutation object of the builder.
func (_u *AccountThrottleRuleUpdate) Mutation() *AccountThrottleRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountThrottleRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountThrottleRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountThrottleRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountThrottleRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountThrottleRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountthrottlerule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountThrottleRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountthrottlerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := accountthrottlerule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.match_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerMode(); ok {
		if err := accountthrottlerule.TriggerModeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.trigger_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := accountthrottlerule.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.action_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountThrottleRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountthrottlerule.Table, accountthrottlerule.Columns, sqlgraph.NewFieldSpec(accountthrottlerule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountthrottlerule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountthrottlerule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(accountthrottlerule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(accountthrottlerule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(accountthrottlerule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(accountthrottlerule.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountthrottlerule.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(accountthrottlerule.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(accountthrottlerule.FieldMatchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerMode(); ok {
		_spec.SetField(accountthrottlerule.FieldTriggerMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccumulatedCount(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccumulatedCount(); ok {
		_spec.AddField(accountthrottlerule.FieldAccumulatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccumulatedWindow(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccumulatedWindow(); ok {
		_spec.AddField(accountthrottlerule.FieldAccumulatedWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(accountthrottlerule.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionDuration(); ok {
		_spec.SetField(accountthrottlerule.FieldActionDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionDuration(); ok {
		_spec.AddField(accountthrottlerule.FieldActionDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionRecoverHour(); ok {
		_spec.SetField(accountthrottlerule.FieldActionRecoverHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionRecoverHour(); ok {
		_spec.AddField(accountthrottlerule.FieldActionRecoverHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Platforms(); ok {
		_spec.SetField(accountthrottlerule.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountthrottlerule.FieldPlatforms, value)
		})
	}
	if _u.mutation.PlatformsCleared() {
		_spec.ClearField(accountthrottlerule.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountthrottlerule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountthrottlerule.FieldDescription, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountthrottlerule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountThrottleRuleUpdateOne is the builder for updating a single AccountThrottleRule entity.
type AccountThrottleRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountThrottleRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountThrottleRuleUpdateOne) SetUpdatedAt(v time.Time) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountThrottleRuleUpdateOne) SetName(v string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableName(v *string) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AccountThrottleRuleUpdateOne) SetEnabled(v bool) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableEnabled(v *bool) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *AccountThrottleRuleUpdateOne) SetPriority(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillablePriority(v *int) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *AccountThrottleRuleUpdateOne) AddPriority(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *AccountThrottleRuleUpdateOne) SetKeywords(v []string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *AccountThrottleRuleUpdateOne) AppendKeywords(v []string) *AccountThrottleRuleUpdateOne {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *AccountThrottleRuleUpdateOne) ClearKeywords() *AccountThrottleRuleUpdateOne {
	_u.mutation.ClearKeywords()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *AccountThrottleRuleUpdateOne) SetMatchMode(v string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableMatchMode(v *string) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// SetTriggerMode sets the "trigger_mode" field.
func (_u *AccountThrottleRuleUpdateOne) SetTriggerMode(v string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetTriggerMode(v)
	return _u
}

// SetNillableTriggerMode sets the "trigger_mode" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableTriggerMode(v *string) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetTriggerMode(*v)
	}
	return _u
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (_u *AccountThrottleRuleUpdateOne) SetAccumulatedCount(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.ResetAccumulatedCount()
	_u.mutation.SetAccumulatedCount(v)
	return _u
}

// SetNillableAccumulatedCount sets the "accumulated_count" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableAccumulatedCount(v *int) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetAccumulatedCount(*v)
	}
	return _u
}

// AddAccumulatedCount adds value to the "accumulated_count" field.
func (_u *AccountThrottleRuleUpdateOne) AddAccumulatedCount(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.AddAccumulatedCount(v)
	return _u
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (_u *AccountThrottleRuleUpdateOne) SetAccumulatedWindow(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.ResetAccumulatedWindow()
	_u.mutation.SetAccumulatedWindow(v)
	return _u
}

// SetNillableAccumulatedWindow sets the "accumulated_window" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableAccumulatedWindow(v *int) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetAccumulatedWindow(*v)
	}
	return _u
}

// AddAccumulatedWindow adds value to the "accumulated_window" field.
func (_u *AccountThrottleRuleUpdateOne) AddAccumulatedWindow(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.AddAccumulatedWindow(v)
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *AccountThrottleRuleUpdateOne) SetActionType(v string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableActionType(v *string) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionDuration sets the "action_duration" field.
func (_u *AccountThrottleRuleUpdateOne) SetActionDuration(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.ResetActionDuration()
	_u.mutation.SetActionDuration(v)
	return _u
}

// SetNillableActionDuration sets the "action_duration" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableActionDuration(v *int) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetActionDuration(*v)
	}
	return _u
}

// AddActionDuration adds value to the "action_duration" field.
func (_u *AccountThrottleRuleUpdateOne) AddActionDuration(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.AddActionDuration(v)
	return _u
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (_u *AccountThrottleRuleUpdateOne) SetActionRecoverHour(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.ResetActionRecoverHour()
	_u.mutation.SetActionRecoverHour(v)
	return _u
}

// SetNillableActionRecoverHour sets the "action_recover_hour" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableActionRecoverHour(v *int) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetActionRecoverHour(*v)
	}
	return _u
}

// AddActionRecoverHour adds value to the "action_recover_hour" field.
func (_u *AccountThrottleRuleUpdateOne) AddActionRecoverHour(v int) *AccountThrottleRuleUpdateOne {
	_u.mutation.AddActionRecoverHour(v)
	return _u
}

// SetPlatforms sets the "platforms" field.
func (_u *AccountThrottleRuleUpdateOne) SetPlatforms(v []string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetPlatforms(v)
	return _u
}

// AppendPlatforms appends value to the "platforms" field.
func (_u *AccountThrottleRuleUpdateOne) AppendPlatforms(v []string) *AccountThrottleRuleUpdateOne {
	_u.mutation.AppendPlatforms(v)
	return _u
}

// ClearPlatforms clears the value of the "platforms" field.
func (_u *AccountThrottleRuleUpdateOne) ClearPlatforms() *AccountThrottleRuleUpdateOne {
	_u.mutation.ClearPlatforms()
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountThrottleRuleUpdateOne) SetDescription(v string) *AccountThrottleRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountThrottleRuleUpdateOne) SetNillableDescription(v *string) *AccountThrottleRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountThrottleRuleUpdateOne) ClearDescription() *AccountThrottleRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AccountThrottleRuleMutation object of the builder.
func (_u *AccountThrottleRuleUpdateOne) Mutation() *AccountThrottleRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountThrottleRuleUpdate builder.
func (_u *AccountThrottleRuleUpdateOne) Where(ps ...predicate.AccountThrottleRule) *AccountThrottleRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountThrottleRuleUpdateOne) Select(field string, fields ...string) *AccountThrottleRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountThrottleRule entity.
func (_u *AccountThrottleRuleUpdateOne) Save(ctx context.Context) (*AccountThrottleRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountThrottleRuleUpdateOne) SaveX(ctx context.Context) *AccountThrottleRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountThrottleRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountThrottleRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountThrottleRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountthrottlerule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountThrottleRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountthrottlerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := accountthrottlerule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.match_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerMode(); ok {
		if err := accountthrottlerule.TriggerModeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.trigger_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionType(); ok {
		if err := accountthrottlerule.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.action_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountThrottleRuleUpdateOne) sqlSave(ctx context.Context) (_node *AccountThrottleRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountthrottlerule.Table, accountthrottlerule.Columns, sqlgraph.NewFieldSpec(accountthrottlerule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountThrottleRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountthrottlerule.FieldID)
		for _, f := range fields {
			if !accountthrottlerule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountthrottlerule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountthrottlerule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountthrottlerule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(accountthrottlerule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(accountthrottlerule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(accountthrottlerule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(accountthrottlerule.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountthrottlerule.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(accountthrottlerule.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(accountthrottlerule.FieldMatchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerMode(); ok {
		_spec.SetField(accountthrottlerule.FieldTriggerMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccumulatedCount(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccumulatedCount(); ok {
		_spec.AddField(accountthrottlerule.FieldAccumulatedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccumulatedWindow(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccumulatedWindow(); ok {
		_spec.AddField(accountthrottlerule.FieldAccumulatedWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(accountthrottlerule.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionDuration(); ok {
		_spec.SetField(accountthrottlerule.FieldActionDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionDuration(); ok {
		_spec.AddField(accountthrottlerule.FieldActionDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionRecoverHour(); ok {
		_spec.SetField(accountthrottlerule.FieldActionRecoverHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActionRecoverHour(); ok {
		_spec.AddField(accountthrottlerule.FieldActionRecoverHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Platforms(); ok {
		_spec.SetField(accountthrottlerule.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountthrottlerule.FieldPlatforms, value)
		})
	}
	if _u.mutation.PlatformsCleared() {
		_spec.ClearField(accountthrottlerule.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountthrottlerule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountthrottlerule.FieldDescription, field.TypeString)
	}
	_node = &AccountThrottleRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountthrottlerule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
