// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountthrottlerule"
)

// AccountThrottleRuleCreate is the builder for creating a AccountThrottleRule entity.
type AccountThrottleRuleCreate struct {
	config
	mutation *AccountThrottleRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountThrottleRuleCreate) SetCreatedAt(v time.Time) *AccountThrottleRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableCreatedAt(v *time.Time) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountThrottleRuleCreate) SetUpdatedAt(v time.Time) *AccountThrottleRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableUpdatedAt(v *time.Time) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountThrottleRuleCreate) SetName(v string) *AccountThrottleRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AccountThrottleRuleCreate) SetEnabled(v bool) *AccountThrottleRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableEnabled(v *bool) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *AccountThrottleRuleCreate) SetPriority(v int) *AccountThrottleRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillablePriority(v *int) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetKeywords sets the "keywords" field.
func (_c *AccountThrottleRuleCreate) SetKeywords(v []string) *AccountThrottleRuleCreate {
	_c.mutation.SetKeywords(v)
	return _c
}

// SetMatchMode sets the "match_mode" field.
func (_c *AccountThrottleRuleCreate) SetMatchMode(v string) *AccountThrottleRuleCreate {
	_c.mutation.SetMatchMode(v)
	return _c
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableMatchMode(v *string) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetMatchMode(*v)
	}
	return _c
}

// SetTriggerMode sets the "trigger_mode" field.
func (_c *AccountThrottleRuleCreate) SetTriggerMode(v string) *AccountThrottleRuleCreate {
	_c.mutation.SetTriggerMode(v)
	return _c
}

// SetNillableTriggerMode sets the "trigger_mode" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableTriggerMode(v *string) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetTriggerMode(*v)
	}
	return _c
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (_c *AccountThrottleRuleCreate) SetAccumulatedCount(v int) *AccountThrottleRuleCreate {
	_c.mutation.SetAccumulatedCount(v)
	return _c
}

// SetNillableAccumulatedCount sets the "accumulated_count" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableAccumulatedCount(v *int) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetAccumulatedCount(*v)
	}
	return _c
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (_c *AccountThrottleRuleCreate) SetAccumulatedWindow(v int) *AccountThrottleRuleCreate {
	_c.mutation.SetAccumulatedWindow(v)
	return _c
}

// SetNillableAccumulatedWindow sets the "accumulated_window" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableAccumulatedWindow(v *int) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetAccumulatedWindow(*v)
	}
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *AccountThrottleRuleCreate) SetActionType(v string) *AccountThrottleRuleCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableActionType(v *string) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetActionType(*v)
	}
	return _c
}

// SetActionDuration sets the "action_duration" field.
func (_c *AccountThrottleRuleCreate) SetActionDuration(v int) *AccountThrottleRuleCreate {
	_c.mutation.SetActionDuration(v)
	return _c
}

// SetNillableActionDuration sets the "action_duration" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableActionDuration(v *int) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetActionDuration(*v)
	}
	return _c
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (_c *AccountThrottleRuleCreate) SetActionRecoverHour(v int) *AccountThrottleRuleCreate {
	_c.mutation.SetActionRecoverHour(v)
	return _c
}

// SetNillableActionRecoverHour sets the "action_recover_hour" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableActionRecoverHour(v *int) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetActionRecoverHour(*v)
	}
	return _c
}

// SetPlatforms sets the "platforms" field.
func (_c *AccountThrottleRuleCreate) SetPlatforms(v []string) *AccountThrottleRuleCreate {
	_c.mutation.SetPlatforms(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AccountThrottleRuleCreate) SetDescription(v string) *AccountThrottleRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AccountThrottleRuleCreate) SetNillableDescription(v *string) *AccountThrottleRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// Mutation returns the AccountThrottleRuleMutation object of the builder.
func (_c *AccountThrottleRuleCreate) Mutation() *AccountThrottleRuleMutation {
	return _c.mutation
}

// Save creates the AccountThrottleRule in the database.
func (_c *AccountThrottleRuleCreate) Save(ctx context.Context) (*AccountThrottleRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountThrottleRuleCreate) SaveX(ctx context.Context) *AccountThrottleRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountThrottleRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountThrottleRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountThrottleRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountthrottlerule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountthrottlerule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := accountthrottlerule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := accountthrottlerule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		v := accountthrottlerule.DefaultMatchMode
		_c.mutation.SetMatchMode(v)
	}
	if _, ok := _c.mutation.TriggerMode(); !ok {
		v := accountthrottlerule.DefaultTriggerMode
		_c.mutation.SetTriggerMode(v)
	}
	if _, ok := _c.mutation.AccumulatedCount(); !ok {
		v := accountthrottlerule.DefaultAccumulatedCount
		_c.mutation.SetAccumulatedCount(v)
	}
	if _, ok := _c.mutation.AccumulatedWindow(); !ok {
		v := accountthrottlerule.DefaultAccumulatedWindow
		_c.mutation.SetAccumulatedWindow(v)
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		v := accountthrottlerule.DefaultActionType
		_c.mutation.SetActionType(v)
	}
	if _, ok := _c.mutation.ActionDuration(); !ok {
		v := accountthrottlerule.DefaultActionDuration
		_c.mutation.SetActionDuration(v)
	}
	if _, ok := _c.mutation.ActionRecoverHour(); !ok {
		v := accountthrottlerule.DefaultActionRecoverHour
		_c.mutation.SetActionRecoverHour(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountThrottleRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountThrottleRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountThrottleRule.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountThrottleRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountthrottlerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AccountThrottleRule.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "AccountThrottleRule.priority"`)}
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		return &ValidationError{Name: "match_mode", err: errors.New(`ent: missing required field "AccountThrottleRule.match_mode"`)}
	}
	if v, ok := _c.mutation.MatchMode(); ok {
		if err := accountthrottlerule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.match_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerMode(); !ok {
		return &ValidationError{Name: "trigger_mode", err: errors.New(`ent: missing required field "AccountThrottleRule.trigger_mode"`)}
	}
	if v, ok := _c.mutation.TriggerMode(); ok {
		if err := accountthrottlerule.TriggerModeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_mode", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.trigger_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccumulatedCount(); !ok {
		return &ValidationError{Name: "accumulated_count", err: errors.New(`ent: missing required field "AccountThrottleRule.accumulated_count"`)}
	}
	if _, ok := _c.mutation.AccumulatedWindow(); !ok {
		return &ValidationError{Name: "accumulated_window", err: errors.New(`ent: missing required field "AccountThrottleRule.accumulated_window"`)}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "AccountThrottleRule.action_type"`)}
	}
	if v, ok := _c.mutation.ActionType(); ok {
		if err := accountthrottlerule.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "AccountThrottleRule.action_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionDuration(); !ok {
		return &ValidationError{Name: "action_duration", err: errors.New(`ent: missing required field "AccountThrottleRule.action_duration"`)}
	}
	if _, ok := _c.mutation.ActionRecoverHour(); !ok {
		return &ValidationError{Name: "action_recover_hour", err: errors.New(`ent: missing required field "AccountThrottleRule.action_recover_hour"`)}
	}
	return nil
}

func (_c *AccountThrottleRuleCreate) sqlSave(ctx context.Context) (*AccountThrottleRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountThrottleRuleCreate) createSpec() (*AccountThrottleRule, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountThrottleRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountthrottlerule.Table, sqlgraph.NewFieldSpec(accountthrottlerule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountthrottlerule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountthrottlerule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountthrottlerule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(accountthrottlerule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(accountthrottlerule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Keywords(); ok {
		_spec.SetField(accountthrottlerule.FieldKeywords, field.TypeJSON, value)
		_node.Keywords = value
	}
	if value, ok := _c.mutation.MatchMode(); ok {
		_spec.SetField(accountthrottlerule.FieldMatchMode, field.TypeString, value)
		_node.MatchMode = value
	}
	if value, ok := _c.mutation.TriggerMode(); ok {
		_spec.SetField(accountthrottlerule.FieldTriggerMode, field.TypeString, value)
		_node.TriggerMode = value
	}
	if value, ok := _c.mutation.AccumulatedCount(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedCount, field.TypeInt, value)
		_node.AccumulatedCount = value
	}
	if value, ok := _c.mutation.AccumulatedWindow(); ok {
		_spec.SetField(accountthrottlerule.FieldAccumulatedWindow, field.TypeInt, value)
		_node.AccumulatedWindow = value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(accountthrottlerule.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.ActionDuration(); ok {
		_spec.SetField(accountthrottlerule.FieldActionDuration, field.TypeInt, value)
		_node.ActionDuration = value
	}
	if value, ok := _c.mutation.ActionRecoverHour(); ok {
		_spec.SetField(accountthrottlerule.FieldActionRecoverHour, field.TypeInt, value)
		_node.ActionRecoverHour = value
	}
	if value, ok := _c.mutation.Platforms(); ok {
		_spec.SetField(accountthrottlerule.FieldPlatforms, field.TypeJSON, value)
		_node.Platforms = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(accountthrottlerule.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountThrottleRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountThrottleRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountThrottleRuleCreate) OnConflict(opts ...sql.ConflictOption) *AccountThrottleRuleUpsertOne {
	_c.conflict = opts
	return &AccountThrottleRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountThrottleRuleCreate) OnConflictColumns(columns ...string) *AccountThrottleRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountThrottleRuleUpsertOne{
		create: _c,
	}
}

type (
	// AccountThrottleRuleUpsertOne is the builder for "upsert"-ing
	//  one AccountThrottleRule node.
	AccountThrottleRuleUpsertOne struct {
		create *AccountThrottleRuleCreate
	}

	// AccountThrottleRuleUpsert is the "OnConflict" setter.
	AccountThrottleRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountThrottleRuleUpsert) SetUpdatedAt(v time.Time) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateUpdatedAt() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountThrottleRuleUpsert) SetName(v string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateName() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AccountThrottleRuleUpsert) SetEnabled(v bool) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateEnabled() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *AccountThrottleRuleUpsert) SetPriority(v int) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdatePriority() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *AccountThrottleRuleUpsert) AddPriority(v int) *AccountThrottleRuleUpsert {
	u.Add(accountthrottlerule.FieldPriority, v)
	return u
}

// SetKeywords sets the "keywords" field.
func (u *AccountThrottleRuleUpsert) SetKeywords(v []string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldKeywords, v)
	return u
}

// UpdateKeywords sets the "keywords" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateKeywords() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldKeywords)
	return u
}

// ClearKeywords clears the value of the "keywords" field.
func (u *AccountThrottleRuleUpsert) ClearKeywords() *AccountThrottleRuleUpsert {
	u.SetNull(accountthrottlerule.FieldKeywords)
	return u
}

// SetMatchMode sets the "match_mode" field.
func (u *AccountThrottleRuleUpsert) SetMatchMode(v string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldMatchMode, v)
	return u
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateMatchMode() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldMatchMode)
	return u
}

// SetTriggerMode sets the "trigger_mode" field.
func (u *AccountThrottleRuleUpsert) SetTriggerMode(v string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldTriggerMode, v)
	return u
}

// UpdateTriggerMode sets the "trigger_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateTriggerMode() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldTriggerMode)
	return u
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (u *AccountThrottleRuleUpsert) SetAccumulatedCount(v int) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldAccumulatedCount, v)
	return u
}

// UpdateAccumulatedCount sets the "accumulated_count" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateAccumulatedCount() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldAccumulatedCount)
	return u
}

// AddAccumulatedCount adds v to the "accumulated_count" field.
func (u *AccountThrottleRuleUpsert) AddAccumulatedCount(v int) *AccountThrottleRuleUpsert {
	u.Add(accountthrottlerule.FieldAccumulatedCount, v)
	return u
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (u *AccountThrottleRuleUpsert) SetAccumulatedWindow(v int) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldAccumulatedWindow, v)
	return u
}

// UpdateAccumulatedWindow sets the "accumulated_window" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateAccumulatedWindow() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldAccumulatedWindow)
	return u
}

// AddAccumulatedWindow adds v to the "accumulated_window" field.
func (u *AccountThrottleRuleUpsert) AddAccumulatedWindow(v int) *AccountThrottleRuleUpsert {
	u.Add(accountthrottlerule.FieldAccumulatedWindow, v)
	return u
}

// SetActionType sets the "action_type" field.
func (u *AccountThrottleRuleUpsert) SetActionType(v string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldActionType, v)
	return u
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateActionType() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldActionType)
	return u
}

// SetActionDuration sets the "action_duration" field.
func (u *AccountThrottleRuleUpsert) SetActionDuration(v int) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldActionDuration, v)
	return u
}

// UpdateActionDuration sets the "action_duration" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateActionDuration() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldActionDuration)
	return u
}

// AddActionDuration adds v to the "action_duration" field.
func (u *AccountThrottleRuleUpsert) AddActionDuration(v int) *AccountThrottleRuleUpsert {
	u.Add(accountthrottlerule.FieldActionDuration, v)
	return u
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsert) SetActionRecoverHour(v int) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldActionRecoverHour, v)
	return u
}

// UpdateActionRecoverHour sets the "action_recover_hour" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateActionRecoverHour() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldActionRecoverHour)
	return u
}

// AddActionRecoverHour adds v to the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsert) AddActionRecoverHour(v int) *AccountThrottleRuleUpsert {
	u.Add(accountthrottlerule.FieldActionRecoverHour, v)
	return u
}

// SetPlatforms sets the "platforms" field.
func (u *AccountThrottleRuleUpsert) SetPlatforms(v []string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldPlatforms, v)
	return u
}

// UpdatePlatforms sets the "platforms" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdatePlatforms() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldPlatforms)
	return u
}

// ClearPlatforms clears the value of the "platforms" field.
func (u *AccountThrottleRuleUpsert) ClearPlatforms() *AccountThrottleRuleUpsert {
	u.SetNull(accountthrottlerule.FieldPlatforms)
	return u
}

// SetDescription sets the "description" field.
func (u *AccountThrottleRuleUpsert) SetDescription(v string) *AccountThrottleRuleUpsert {
	u.Set(accountthrottlerule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsert) UpdateDescription() *AccountThrottleRuleUpsert {
	u.SetExcluded(accountthrottlerule.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AccountThrottleRuleUpsert) ClearDescription() *AccountThrottleRuleUpsert {
	u.SetNull(accountthrottlerule.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountThrottleRuleUpsertOne) UpdateNewValues() *AccountThrottleRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountthrottlerule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountThrottleRuleUpsertOne) Ignore() *AccountThrottleRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountThrottleRuleUpsertOne) DoNothing() *AccountThrottleRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountThrottleRuleCreate.OnConflict
// documentation for more info.
func (u *AccountThrottleRuleUpsertOne) Update(set func(*AccountThrottleRuleUpsert)) *AccountThrottleRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountThrottleRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountThrottleRuleUpsertOne) SetUpdatedAt(v time.Time) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateUpdatedAt() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountThrottleRuleUpsertOne) SetName(v string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateName() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AccountThrottleRuleUpsertOne) SetEnabled(v bool) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateEnabled() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *AccountThrottleRuleUpsertOne) SetPriority(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *AccountThrottleRuleUpsertOne) AddPriority(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdatePriority() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetKeywords sets the "keywords" field.
func (u *AccountThrottleRuleUpsertOne) SetKeywords(v []string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetKeywords(v)
	})
}

// UpdateKeywords sets the "keywords" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateKeywords() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateKeywords()
	})
}

// ClearKeywords clears the value of the "keywords" field.
func (u *AccountThrottleRuleUpsertOne) ClearKeywords() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearKeywords()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *AccountThrottleRuleUpsertOne) SetMatchMode(v string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateMatchMode() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateMatchMode()
	})
}

// SetTriggerMode sets the "trigger_mode" field.
func (u *AccountThrottleRuleUpsertOne) SetTriggerMode(v string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetTriggerMode(v)
	})
}

// UpdateTriggerMode sets the "trigger_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateTriggerMode() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateTriggerMode()
	})
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (u *AccountThrottleRuleUpsertOne) SetAccumulatedCount(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetAccumulatedCount(v)
	})
}

// AddAccumulatedCount adds v to the "accumulated_count" field.
func (u *AccountThrottleRuleUpsertOne) AddAccumulatedCount(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddAccumulatedCount(v)
	})
}

// UpdateAccumulatedCount sets the "accumulated_count" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateAccumulatedCount() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateAccumulatedCount()
	})
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (u *AccountThrottleRuleUpsertOne) SetAccumulatedWindow(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetAccumulatedWindow(v)
	})
}

// AddAccumulatedWindow adds v to the "accumulated_window" field.
func (u *AccountThrottleRuleUpsertOne) AddAccumulatedWindow(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddAccumulatedWindow(v)
	})
}

// UpdateAccumulatedWindow sets the "accumulated_window" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateAccumulatedWindow() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateAccumulatedWindow()
	})
}

// SetActionType sets the "action_type" field.
func (u *AccountThrottleRuleUpsertOne) SetActionType(v string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateActionType() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionType()
	})
}

// SetActionDuration sets the "action_duration" field.
func (u *AccountThrottleRuleUpsertOne) SetActionDuration(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionDuration(v)
	})
}

// AddActionDuration adds v to the "action_duration" field.
func (u *AccountThrottleRuleUpsertOne) AddActionDuration(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddActionDuration(v)
	})
}

// UpdateActionDuration sets the "action_duration" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateActionDuration() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionDuration()
	})
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsertOne) SetActionRecoverHour(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionRecoverHour(v)
	})
}

// AddActionRecoverHour adds v to the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsertOne) AddActionRecoverHour(v int) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddActionRecoverHour(v)
	})
}

// UpdateActionRecoverHour sets the "action_recover_hour" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateActionRecoverHour() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionRecoverHour()
	})
}

// SetPlatforms sets the "platforms" field.
func (u *AccountThrottleRuleUpsertOne) SetPlatforms(v []string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetPlatforms(v)
	})
}

// UpdatePlatforms sets the "platforms" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdatePlatforms() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdatePlatforms()
	})
}

// ClearPlatforms clears the value of the "platforms" field.
func (u *AccountThrottleRuleUpsertOne) ClearPlatforms() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearPlatforms()
	})
}

// SetDescription sets the "description" field.
func (u *AccountThrottleRuleUpsertOne) SetDescription(v string) *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertOne) UpdateDescription() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountThrottleRuleUpsertOne) ClearDescription() *AccountThrottleRuleUpsertOne {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *AccountThrottleRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountThrottleRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountThrottleRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountThrottleRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountThrottleRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountThrottleRuleCreateBulk is the builder for creating many AccountThrottleRule entities in bulk.
type AccountThrottleRuleCreateBulk struct {
	config
	err      error
	builders []*AccountThrottleRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountThrottleRule entities in the database.
func (_c *AccountThrottleRuleCreateBulk) Save(ctx context.Context) ([]*AccountThrottleRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountThrottleRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountThrottleRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountThrottleRuleCreateBulk) SaveX(ctx context.Context) []*AccountThrottleRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountThrottleRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountThrottleRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountThrottleRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountThrottleRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountThrottleRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountThrottleRuleUpsertBulk {
	_c.conflict = opts
	return &AccountThrottleRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountThrottleRuleCreateBulk) OnConflictColumns(columns ...string) *AccountThrottleRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountThrottleRuleUpsertBulk{
		create: _c,
	}
}

// AccountThrottleRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountThrottleRule nodes.
type AccountThrottleRuleUpsertBulk struct {
	create *AccountThrottleRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountThrottleRuleUpsertBulk) UpdateNewValues() *AccountThrottleRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountthrottlerule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountThrottleRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountThrottleRuleUpsertBulk) Ignore() *AccountThrottleRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountThrottleRuleUpsertBulk) DoNothing() *AccountThrottleRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountThrottleRuleCreateBulk.OnConflict
// documentation for more info.
func (u *AccountThrottleRuleUpsertBulk) Update(set func(*AccountThrottleRuleUpsert)) *AccountThrottleRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountThrottleRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountThrottleRuleUpsertBulk) SetUpdatedAt(v time.Time) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateUpdatedAt() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountThrottleRuleUpsertBulk) SetName(v string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateName() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AccountThrottleRuleUpsertBulk) SetEnabled(v bool) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateEnabled() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *AccountThrottleRuleUpsertBulk) SetPriority(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *AccountThrottleRuleUpsertBulk) AddPriority(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdatePriority() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetKeywords sets the "keywords" field.
func (u *AccountThrottleRuleUpsertBulk) SetKeywords(v []string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetKeywords(v)
	})
}

// UpdateKeywords sets the "keywords" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateKeywords() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateKeywords()
	})
}

// ClearKeywords clears the value of the "keywords" field.
func (u *AccountThrottleRuleUpsertBulk) ClearKeywords() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearKeywords()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *AccountThrottleRuleUpsertBulk) SetMatchMode(v string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateMatchMode() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateMatchMode()
	})
}

// SetTriggerMode sets the "trigger_mode" field.
func (u *AccountThrottleRuleUpsertBulk) SetTriggerMode(v string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetTriggerMode(v)
	})
}

// UpdateTriggerMode sets the "trigger_mode" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateTriggerMode() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateTriggerMode()
	})
}

// SetAccumulatedCount sets the "accumulated_count" field.
func (u *AccountThrottleRuleUpsertBulk) SetAccumulatedCount(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetAccumulatedCount(v)
	})
}

// AddAccumulatedCount adds v to the "accumulated_count" field.
func (u *AccountThrottleRuleUpsertBulk) AddAccumulatedCount(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddAccumulatedCount(v)
	})
}

// UpdateAccumulatedCount sets the "accumulated_count" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateAccumulatedCount() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateAccumulatedCount()
	})
}

// SetAccumulatedWindow sets the "accumulated_window" field.
func (u *AccountThrottleRuleUpsertBulk) SetAccumulatedWindow(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetAccumulatedWindow(v)
	})
}

// AddAccumulatedWindow adds v to the "accumulated_window" field.
func (u *AccountThrottleRuleUpsertBulk) AddAccumulatedWindow(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddAccumulatedWindow(v)
	})
}

// UpdateAccumulatedWindow sets the "accumulated_window" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateAccumulatedWindow() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateAccumulatedWindow()
	})
}

// SetActionType sets the "action_type" field.
func (u *AccountThrottleRuleUpsertBulk) SetActionType(v string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateActionType() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionType()
	})
}

// SetActionDuration sets the "action_duration" field.
func (u *AccountThrottleRuleUpsertBulk) SetActionDuration(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionDuration(v)
	})
}

// AddActionDuration adds v to the "action_duration" field.
func (u *AccountThrottleRuleUpsertBulk) AddActionDuration(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddActionDuration(v)
	})
}

// UpdateActionDuration sets the "action_duration" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateActionDuration() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionDuration()
	})
}

// SetActionRecoverHour sets the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsertBulk) SetActionRecoverHour(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetActionRecoverHour(v)
	})
}

// AddActionRecoverHour adds v to the "action_recover_hour" field.
func (u *AccountThrottleRuleUpsertBulk) AddActionRecoverHour(v int) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.AddActionRecoverHour(v)
	})
}

// UpdateActionRecoverHour sets the "action_recover_hour" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateActionRecoverHour() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateActionRecoverHour()
	})
}

// SetPlatforms sets the "platforms" field.
func (u *AccountThrottleRuleUpsertBulk) SetPlatforms(v []string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetPlatforms(v)
	})
}

// UpdatePlatforms sets the "platforms" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdatePlatforms() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdatePlatforms()
	})
}

// ClearPlatforms clears the value of the "platforms" field.
func (u *AccountThrottleRuleUpsertBulk) ClearPlatforms() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearPlatforms()
	})
}

// SetDescription sets the "description" field.
func (u *AccountThrottleRuleUpsertBulk) SetDescription(v string) *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountThrottleRuleUpsertBulk) UpdateDescription() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountThrottleRuleUpsertBulk) ClearDescription() *AccountThrottleRuleUpsertBulk {
	return u.Update(func(s *AccountThrottleRuleUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *AccountThrottleRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountThrottleRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountThrottleRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountThrottleRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
