// Code generated by ent, DO NOT EDIT.

package accountthrottlerule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountthrottlerule type in the database.
	Label = "account_throttle_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldErrorCodes holds the string denoting the error_codes field in the database.
	FieldErrorCodes = "error_codes"
	// FieldKeywords holds the string denoting the keywords field in the database.
	FieldKeywords = "keywords"
	// FieldMatchMode holds the string denoting the match_mode field in the database.
	FieldMatchMode = "match_mode"
	// FieldTriggerMode holds the string denoting the trigger_mode field in the database.
	FieldTriggerMode = "trigger_mode"
	// FieldAccumulatedCount holds the string denoting the accumulated_count field in the database.
	FieldAccumulatedCount = "accumulated_count"
	// FieldAccumulatedWindow holds the string denoting the accumulated_window field in the database.
	FieldAccumulatedWindow = "accumulated_window"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldActionDuration holds the string denoting the action_duration field in the database.
	FieldActionDuration = "action_duration"
	// FieldActionRecoverHour holds the string denoting the action_recover_hour field in the database.
	FieldActionRecoverHour = "action_recover_hour"
	// FieldRecoveryCheckInterval holds the string denoting the recovery_check_interval field in the database.
	FieldRecoveryCheckInterval = "recovery_check_interval"
	// FieldPlatforms holds the string denoting the platforms field in the database.
	FieldPlatforms = "platforms"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the accountthrottlerule in the database.
	Table = "account_throttle_rules"
)

// Columns holds all SQL columns for accountthrottlerule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEnabled,
	FieldPriority,
	FieldErrorCodes,
	FieldKeywords,
	FieldMatchMode,
	FieldTriggerMode,
	FieldAccumulatedCount,
	FieldAccumulatedWindow,
	FieldActionType,
	FieldActionDuration,
	FieldActionRecoverHour,
	FieldRecoveryCheckInterval,
	FieldPlatforms,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultMatchMode holds the default value on creation for the "match_mode" field.
	DefaultMatchMode string
	// MatchModeValidator is a validator for the "match_mode" field. It is called by the builders before save.
	MatchModeValidator func(string) error
	// DefaultTriggerMode holds the default value on creation for the "trigger_mode" field.
	DefaultTriggerMode string
	// TriggerModeValidator is a validator for the "trigger_mode" field. It is called by the builders before save.
	TriggerModeValidator func(string) error
	// DefaultAccumulatedCount holds the default value on creation for the "accumulated_count" field.
	DefaultAccumulatedCount int
	// DefaultAccumulatedWindow holds the default value on creation for the "accumulated_window" field.
	DefaultAccumulatedWindow int
	// DefaultActionType holds the default value on creation for the "action_type" field.
	DefaultActionType string
	// ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	ActionTypeValidator func(string) error
	// DefaultActionDuration holds the default value on creation for the "action_duration" field.
	DefaultActionDuration int
	// DefaultActionRecoverHour holds the default value on creation for the "action_recover_hour" field.
	DefaultActionRecoverHour int
	// DefaultRecoveryCheckInterval holds the default value on creation for the "recovery_check_interval" field.
	DefaultRecoveryCheckInterval int
)

// OrderOption defines the ordering options for the AccountThrottleRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByMatchMode orders the results by the match_mode field.
func ByMatchMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchMode, opts...).ToFunc()
}

// ByTriggerMode orders the results by the trigger_mode field.
func ByTriggerMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerMode, opts...).ToFunc()
}

// ByAccumulatedCount orders the results by the accumulated_count field.
func ByAccumulatedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccumulatedCount, opts...).ToFunc()
}

// ByAccumulatedWindow orders the results by the accumulated_window field.
func ByAccumulatedWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccumulatedWindow, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByActionDuration orders the results by the action_duration field.
func ByActionDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionDuration, opts...).ToFunc()
}

// ByActionRecoverHour orders the results by the action_recover_hour field.
func ByActionRecoverHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionRecoverHour, opts...).ToFunc()
}

// ByRecoveryCheckInterval orders the results by the recovery_check_interval field.
func ByRecoveryCheckInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecoveryCheckInterval, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}
