// Code generated by ent, DO NOT EDIT.

package accountthrottlerule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldPriority, v))
}

// MatchMode applies equality check predicate on the "match_mode" field. It's identical to MatchModeEQ.
func MatchMode(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldMatchMode, v))
}

// TriggerMode applies equality check predicate on the "trigger_mode" field. It's identical to TriggerModeEQ.
func TriggerMode(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldTriggerMode, v))
}

// AccumulatedCount applies equality check predicate on the "accumulated_count" field. It's identical to AccumulatedCountEQ.
func AccumulatedCount(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldAccumulatedCount, v))
}

// AccumulatedWindow applies equality check predicate on the "accumulated_window" field. It's identical to AccumulatedWindowEQ.
func AccumulatedWindow(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldAccumulatedWindow, v))
}

// ActionType applies equality check predicate on the "action_type" field. It's identical to ActionTypeEQ.
func ActionType(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionType, v))
}

// ActionDuration applies equality check predicate on the "action_duration" field. It's identical to ActionDurationEQ.
func ActionDuration(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionDuration, v))
}

// ActionRecoverHour applies equality check predicate on the "action_recover_hour" field. It's identical to ActionRecoverHourEQ.
func ActionRecoverHour(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionRecoverHour, v))
}

// RecoveryCheckInterval applies equality check predicate on the "recovery_check_interval" field. It's identical to RecoveryCheckIntervalEQ.
func RecoveryCheckInterval(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldRecoveryCheckInterval, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldPriority, v))
}

// ErrorCodesIsNil applies the IsNil predicate on the "error_codes" field.
func ErrorCodesIsNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIsNull(FieldErrorCodes))
}

// ErrorCodesNotNil applies the NotNil predicate on the "error_codes" field.
func ErrorCodesNotNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotNull(FieldErrorCodes))
}

// KeywordsIsNil applies the IsNil predicate on the "keywords" field.
func KeywordsIsNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIsNull(FieldKeywords))
}

// KeywordsNotNil applies the NotNil predicate on the "keywords" field.
func KeywordsNotNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotNull(FieldKeywords))
}

// MatchModeEQ applies the EQ predicate on the "match_mode" field.
func MatchModeEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldMatchMode, v))
}

// MatchModeNEQ applies the NEQ predicate on the "match_mode" field.
func MatchModeNEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldMatchMode, v))
}

// MatchModeIn applies the In predicate on the "match_mode" field.
func MatchModeIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldMatchMode, vs...))
}

// MatchModeNotIn applies the NotIn predicate on the "match_mode" field.
func MatchModeNotIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldMatchMode, vs...))
}

// MatchModeGT applies the GT predicate on the "match_mode" field.
func MatchModeGT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldMatchMode, v))
}

// MatchModeGTE applies the GTE predicate on the "match_mode" field.
func MatchModeGTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldMatchMode, v))
}

// MatchModeLT applies the LT predicate on the "match_mode" field.
func MatchModeLT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldMatchMode, v))
}

// MatchModeLTE applies the LTE predicate on the "match_mode" field.
func MatchModeLTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldMatchMode, v))
}

// MatchModeContains applies the Contains predicate on the "match_mode" field.
func MatchModeContains(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContains(FieldMatchMode, v))
}

// MatchModeHasPrefix applies the HasPrefix predicate on the "match_mode" field.
func MatchModeHasPrefix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasPrefix(FieldMatchMode, v))
}

// MatchModeHasSuffix applies the HasSuffix predicate on the "match_mode" field.
func MatchModeHasSuffix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasSuffix(FieldMatchMode, v))
}

// MatchModeEqualFold applies the EqualFold predicate on the "match_mode" field.
func MatchModeEqualFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEqualFold(FieldMatchMode, v))
}

// MatchModeContainsFold applies the ContainsFold predicate on the "match_mode" field.
func MatchModeContainsFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContainsFold(FieldMatchMode, v))
}

// TriggerModeEQ applies the EQ predicate on the "trigger_mode" field.
func TriggerModeEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldTriggerMode, v))
}

// TriggerModeNEQ applies the NEQ predicate on the "trigger_mode" field.
func TriggerModeNEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldTriggerMode, v))
}

// TriggerModeIn applies the In predicate on the "trigger_mode" field.
func TriggerModeIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldTriggerMode, vs...))
}

// TriggerModeNotIn applies the NotIn predicate on the "trigger_mode" field.
func TriggerModeNotIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldTriggerMode, vs...))
}

// TriggerModeGT applies the GT predicate on the "trigger_mode" field.
func TriggerModeGT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldTriggerMode, v))
}

// TriggerModeGTE applies the GTE predicate on the "trigger_mode" field.
func TriggerModeGTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldTriggerMode, v))
}

// TriggerModeLT applies the LT predicate on the "trigger_mode" field.
func TriggerModeLT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldTriggerMode, v))
}

// TriggerModeLTE applies the LTE predicate on the "trigger_mode" field.
func TriggerModeLTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldTriggerMode, v))
}

// TriggerModeContains applies the Contains predicate on the "trigger_mode" field.
func TriggerModeContains(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContains(FieldTriggerMode, v))
}

// TriggerModeHasPrefix applies the HasPrefix predicate on the "trigger_mode" field.
func TriggerModeHasPrefix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasPrefix(FieldTriggerMode, v))
}

// TriggerModeHasSuffix applies the HasSuffix predicate on the "trigger_mode" field.
func TriggerModeHasSuffix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasSuffix(FieldTriggerMode, v))
}

// TriggerModeEqualFold applies the EqualFold predicate on the "trigger_mode" field.
func TriggerModeEqualFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEqualFold(FieldTriggerMode, v))
}

// TriggerModeContainsFold applies the ContainsFold predicate on the "trigger_mode" field.
func TriggerModeContainsFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContainsFold(FieldTriggerMode, v))
}

// AccumulatedCountEQ applies the EQ predicate on the "accumulated_count" field.
func AccumulatedCountEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldAccumulatedCount, v))
}

// AccumulatedCountNEQ applies the NEQ predicate on the "accumulated_count" field.
func AccumulatedCountNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldAccumulatedCount, v))
}

// AccumulatedCountIn applies the In predicate on the "accumulated_count" field.
func AccumulatedCountIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldAccumulatedCount, vs...))
}

// AccumulatedCountNotIn applies the NotIn predicate on the "accumulated_count" field.
func AccumulatedCountNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldAccumulatedCount, vs...))
}

// AccumulatedCountGT applies the GT predicate on the "accumulated_count" field.
func AccumulatedCountGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldAccumulatedCount, v))
}

// AccumulatedCountGTE applies the GTE predicate on the "accumulated_count" field.
func AccumulatedCountGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldAccumulatedCount, v))
}

// AccumulatedCountLT applies the LT predicate on the "accumulated_count" field.
func AccumulatedCountLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldAccumulatedCount, v))
}

// AccumulatedCountLTE applies the LTE predicate on the "accumulated_count" field.
func AccumulatedCountLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldAccumulatedCount, v))
}

// AccumulatedWindowEQ applies the EQ predicate on the "accumulated_window" field.
func AccumulatedWindowEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldAccumulatedWindow, v))
}

// AccumulatedWindowNEQ applies the NEQ predicate on the "accumulated_window" field.
func AccumulatedWindowNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldAccumulatedWindow, v))
}

// AccumulatedWindowIn applies the In predicate on the "accumulated_window" field.
func AccumulatedWindowIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldAccumulatedWindow, vs...))
}

// AccumulatedWindowNotIn applies the NotIn predicate on the "accumulated_window" field.
func AccumulatedWindowNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldAccumulatedWindow, vs...))
}

// AccumulatedWindowGT applies the GT predicate on the "accumulated_window" field.
func AccumulatedWindowGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldAccumulatedWindow, v))
}

// AccumulatedWindowGTE applies the GTE predicate on the "accumulated_window" field.
func AccumulatedWindowGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldAccumulatedWindow, v))
}

// AccumulatedWindowLT applies the LT predicate on the "accumulated_window" field.
func AccumulatedWindowLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldAccumulatedWindow, v))
}

// AccumulatedWindowLTE applies the LTE predicate on the "accumulated_window" field.
func AccumulatedWindowLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldAccumulatedWindow, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldActionType, vs...))
}

// ActionTypeGT applies the GT predicate on the "action_type" field.
func ActionTypeGT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldActionType, v))
}

// ActionTypeGTE applies the GTE predicate on the "action_type" field.
func ActionTypeGTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldActionType, v))
}

// ActionTypeLT applies the LT predicate on the "action_type" field.
func ActionTypeLT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldActionType, v))
}

// ActionTypeLTE applies the LTE predicate on the "action_type" field.
func ActionTypeLTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldActionType, v))
}

// ActionTypeContains applies the Contains predicate on the "action_type" field.
func ActionTypeContains(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContains(FieldActionType, v))
}

// ActionTypeHasPrefix applies the HasPrefix predicate on the "action_type" field.
func ActionTypeHasPrefix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasPrefix(FieldActionType, v))
}

// ActionTypeHasSuffix applies the HasSuffix predicate on the "action_type" field.
func ActionTypeHasSuffix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasSuffix(FieldActionType, v))
}

// ActionTypeEqualFold applies the EqualFold predicate on the "action_type" field.
func ActionTypeEqualFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEqualFold(FieldActionType, v))
}

// ActionTypeContainsFold applies the ContainsFold predicate on the "action_type" field.
func ActionTypeContainsFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContainsFold(FieldActionType, v))
}

// ActionDurationEQ applies the EQ predicate on the "action_duration" field.
func ActionDurationEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionDuration, v))
}

// ActionDurationNEQ applies the NEQ predicate on the "action_duration" field.
func ActionDurationNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldActionDuration, v))
}

// ActionDurationIn applies the In predicate on the "action_duration" field.
func ActionDurationIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldActionDuration, vs...))
}

// ActionDurationNotIn applies the NotIn predicate on the "action_duration" field.
func ActionDurationNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldActionDuration, vs...))
}

// ActionDurationGT applies the GT predicate on the "action_duration" field.
func ActionDurationGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldActionDuration, v))
}

// ActionDurationGTE applies the GTE predicate on the "action_duration" field.
func ActionDurationGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldActionDuration, v))
}

// ActionDurationLT applies the LT predicate on the "action_duration" field.
func ActionDurationLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldActionDuration, v))
}

// ActionDurationLTE applies the LTE predicate on the "action_duration" field.
func ActionDurationLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldActionDuration, v))
}

// ActionRecoverHourEQ applies the EQ predicate on the "action_recover_hour" field.
func ActionRecoverHourEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldActionRecoverHour, v))
}

// ActionRecoverHourNEQ applies the NEQ predicate on the "action_recover_hour" field.
func ActionRecoverHourNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldActionRecoverHour, v))
}

// ActionRecoverHourIn applies the In predicate on the "action_recover_hour" field.
func ActionRecoverHourIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldActionRecoverHour, vs...))
}

// ActionRecoverHourNotIn applies the NotIn predicate on the "action_recover_hour" field.
func ActionRecoverHourNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldActionRecoverHour, vs...))
}

// ActionRecoverHourGT applies the GT predicate on the "action_recover_hour" field.
func ActionRecoverHourGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldActionRecoverHour, v))
}

// ActionRecoverHourGTE applies the GTE predicate on the "action_recover_hour" field.
func ActionRecoverHourGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldActionRecoverHour, v))
}

// ActionRecoverHourLT applies the LT predicate on the "action_recover_hour" field.
func ActionRecoverHourLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldActionRecoverHour, v))
}

// ActionRecoverHourLTE applies the LTE predicate on the "action_recover_hour" field.
func ActionRecoverHourLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldActionRecoverHour, v))
}

// RecoveryCheckIntervalEQ applies the EQ predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldRecoveryCheckInterval, v))
}

// RecoveryCheckIntervalNEQ applies the NEQ predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalNEQ(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldRecoveryCheckInterval, v))
}

// RecoveryCheckIntervalIn applies the In predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldRecoveryCheckInterval, vs...))
}

// RecoveryCheckIntervalNotIn applies the NotIn predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalNotIn(vs ...int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldRecoveryCheckInterval, vs...))
}

// RecoveryCheckIntervalGT applies the GT predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalGT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldRecoveryCheckInterval, v))
}

// RecoveryCheckIntervalGTE applies the GTE predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalGTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldRecoveryCheckInterval, v))
}

// RecoveryCheckIntervalLT applies the LT predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalLT(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldRecoveryCheckInterval, v))
}

// RecoveryCheckIntervalLTE applies the LTE predicate on the "recovery_check_interval" field.
func RecoveryCheckIntervalLTE(v int) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldRecoveryCheckInterval, v))
}

// PlatformsIsNil applies the IsNil predicate on the "platforms" field.
func PlatformsIsNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIsNull(FieldPlatforms))
}

// PlatformsNotNil applies the NotNil predicate on the "platforms" field.
func PlatformsNotNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotNull(FieldPlatforms))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.FieldContainsFold(FieldDescription, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountThrottleRule) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountThrottleRule) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountThrottleRule) predicate.AccountThrottleRule {
	return predicate.AccountThrottleRule(sql.NotPredicates(p))
}
